//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicles
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", ConfigurationName="Vehicles.VehiclesBasics_Port")]
    public interface VehiclesBasics_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.Read_Result Read(Vehicles.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.Read_Result> ReadAsync(Vehicles.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.ReadByRecId_Result ReadByRecId(Vehicles.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.ReadByRecId_Result> ReadByRecIdAsync(Vehicles.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.ReadMultiple_Result ReadMultiple(Vehicles.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.ReadMultiple_Result> ReadMultipleAsync(Vehicles.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.IsUpdated_Result IsUpdated(Vehicles.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.IsUpdated_Result> IsUpdatedAsync(Vehicles.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.GetRecIdFromKey_Result GetRecIdFromKey(Vehicles.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Vehicles.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.Create_Result Create(Vehicles.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.Create_Result> CreateAsync(Vehicles.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.CreateMultiple_Result CreateMultiple(Vehicles.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.CreateMultiple_Result> CreateMultipleAsync(Vehicles.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.Update_Result Update(Vehicles.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.Update_Result> UpdateAsync(Vehicles.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.UpdateMultiple_Result UpdateMultiple(Vehicles.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.UpdateMultiple_Result> UpdateMultipleAsync(Vehicles.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vehicles.Delete_Result Delete(Vehicles.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vehiclesbasics:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Vehicles.Delete_Result> DeleteAsync(Vehicles.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics")]
    public partial class VehiclesBasics
    {
        
        private string keyField;
        
        private string vehicle_NumberField;
        
        private Vehicle_Type vehicle_TypeField;
        
        private bool vehicle_TypeFieldSpecified;
        
        private System.DateTime start_DateField;
        
        private bool start_DateFieldSpecified;
        
        private string codeField;
        
        private string categoryField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string fleet_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Vehicle_Number
        {
            get
            {
                return this.vehicle_NumberField;
            }
            set
            {
                this.vehicle_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Vehicle_Type Vehicle_Type
        {
            get
            {
                return this.vehicle_TypeField;
            }
            set
            {
                this.vehicle_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Vehicle_TypeSpecified
        {
            get
            {
                return this.vehicle_TypeFieldSpecified;
            }
            set
            {
                this.vehicle_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime Start_Date
        {
            get
            {
                return this.start_DateField;
            }
            set
            {
                this.start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_DateSpecified
        {
            get
            {
                return this.start_DateFieldSpecified;
            }
            set
            {
                this.start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Fleet_No
        {
            get
            {
                return this.fleet_NoField;
            }
            set
            {
                this.fleet_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics")]
    public enum Vehicle_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        _x0031_4_Seater,
        
        /// <remarks/>
        _x0033_3_Seater,
        
        /// <remarks/>
        _x0032_5_Seater,
        
        /// <remarks/>
        _x0032_9_Seater,
        
        /// <remarks/>
        _41_Seater,
        
        /// <remarks/>
        _26_Seater,
        
        /// <remarks/>
        _37_Seater,
        
        /// <remarks/>
        _x0035_1_Seater,
        
        /// <remarks/>
        _x0033_4_Seater,
        
        /// <remarks/>
        _x0033_8_Seater,
        
        /// <remarks/>
        _x0034_0_Seater,
        
        /// <remarks/>
        _x0034_6_Seater,
        
        /// <remarks/>
        _x0036_0_Seater,
        
        /// <remarks/>
        _x0033_5_Seater,
        
        /// <remarks/>
        _x0033_6_Seater,
        
        /// <remarks/>
        _x0033_9_Seater,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics")]
    public enum Status
    {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Dormant,
        
        /// <remarks/>
        Left,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics")]
    public partial class VehiclesBasics_Filter
    {
        
        private VehiclesBasics_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehiclesBasics_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics")]
    public enum VehiclesBasics_Fields
    {
        
        /// <remarks/>
        Vehicle_Number,
        
        /// <remarks/>
        Vehicle_Type,
        
        /// <remarks/>
        Start_Date,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Category,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Fleet_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public string Vehicle_Number;
        
        public Read()
        {
        }
        
        public Read(string Vehicle_Number)
        {
            this.Vehicle_Number = Vehicle_Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public Vehicles.VehiclesBasics VehiclesBasics;
        
        public Read_Result()
        {
        }
        
        public Read_Result(Vehicles.VehiclesBasics VehiclesBasics)
        {
            this.VehiclesBasics = VehiclesBasics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public Vehicles.VehiclesBasics VehiclesBasics;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(Vehicles.VehiclesBasics VehiclesBasics)
        {
            this.VehiclesBasics = VehiclesBasics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Vehicles.VehiclesBasics_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(Vehicles.VehiclesBasics_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Vehicles.VehiclesBasics[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(Vehicles.VehiclesBasics[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public Vehicles.VehiclesBasics VehiclesBasics;
        
        public Create()
        {
        }
        
        public Create(Vehicles.VehiclesBasics VehiclesBasics)
        {
            this.VehiclesBasics = VehiclesBasics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public Vehicles.VehiclesBasics VehiclesBasics;
        
        public Create_Result()
        {
        }
        
        public Create_Result(Vehicles.VehiclesBasics VehiclesBasics)
        {
            this.VehiclesBasics = VehiclesBasics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Vehicles.VehiclesBasics[] VehiclesBasics_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(Vehicles.VehiclesBasics[] VehiclesBasics_List)
        {
            this.VehiclesBasics_List = VehiclesBasics_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Vehicles.VehiclesBasics[] VehiclesBasics_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(Vehicles.VehiclesBasics[] VehiclesBasics_List)
        {
            this.VehiclesBasics_List = VehiclesBasics_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public Vehicles.VehiclesBasics VehiclesBasics;
        
        public Update()
        {
        }
        
        public Update(Vehicles.VehiclesBasics VehiclesBasics)
        {
            this.VehiclesBasics = VehiclesBasics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public Vehicles.VehiclesBasics VehiclesBasics;
        
        public Update_Result()
        {
        }
        
        public Update_Result(Vehicles.VehiclesBasics VehiclesBasics)
        {
            this.VehiclesBasics = VehiclesBasics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Vehicles.VehiclesBasics[] VehiclesBasics_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(Vehicles.VehiclesBasics[] VehiclesBasics_List)
        {
            this.VehiclesBasics_List = VehiclesBasics_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Vehicles.VehiclesBasics[] VehiclesBasics_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(Vehicles.VehiclesBasics[] VehiclesBasics_List)
        {
            this.VehiclesBasics_List = VehiclesBasics_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/vehiclesbasics", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface VehiclesBasics_PortChannel : Vehicles.VehiclesBasics_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VehiclesBasics_PortClient : System.ServiceModel.ClientBase<Vehicles.VehiclesBasics_Port>, Vehicles.VehiclesBasics_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VehiclesBasics_PortClient() : 
                base(VehiclesBasics_PortClient.GetDefaultBinding(), VehiclesBasics_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.VehiclesBasics_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehiclesBasics_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(VehiclesBasics_PortClient.GetBindingForEndpoint(endpointConfiguration), VehiclesBasics_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehiclesBasics_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VehiclesBasics_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehiclesBasics_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VehiclesBasics_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehiclesBasics_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.Read_Result Vehicles.VehiclesBasics_Port.Read(Vehicles.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public Vehicles.VehiclesBasics Read(string Vehicle_Number)
        {
            Vehicles.Read inValue = new Vehicles.Read();
            inValue.Vehicle_Number = Vehicle_Number;
            Vehicles.Read_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).Read(inValue);
            return retVal.VehiclesBasics;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vehicles.Read_Result> Vehicles.VehiclesBasics_Port.ReadAsync(Vehicles.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vehicles.Read_Result> ReadAsync(string Vehicle_Number)
        {
            Vehicles.Read inValue = new Vehicles.Read();
            inValue.Vehicle_Number = Vehicle_Number;
            return ((Vehicles.VehiclesBasics_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.ReadByRecId_Result Vehicles.VehiclesBasics_Port.ReadByRecId(Vehicles.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public Vehicles.VehiclesBasics ReadByRecId(string recId)
        {
            Vehicles.ReadByRecId inValue = new Vehicles.ReadByRecId();
            inValue.recId = recId;
            Vehicles.ReadByRecId_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).ReadByRecId(inValue);
            return retVal.VehiclesBasics;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vehicles.ReadByRecId_Result> Vehicles.VehiclesBasics_Port.ReadByRecIdAsync(Vehicles.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vehicles.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            Vehicles.ReadByRecId inValue = new Vehicles.ReadByRecId();
            inValue.recId = recId;
            return ((Vehicles.VehiclesBasics_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.ReadMultiple_Result Vehicles.VehiclesBasics_Port.ReadMultiple(Vehicles.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public Vehicles.VehiclesBasics[] ReadMultiple(Vehicles.VehiclesBasics_Filter[] filter, string bookmarkKey, int setSize)
        {
            Vehicles.ReadMultiple inValue = new Vehicles.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Vehicles.ReadMultiple_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vehicles.ReadMultiple_Result> Vehicles.VehiclesBasics_Port.ReadMultipleAsync(Vehicles.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vehicles.ReadMultiple_Result> ReadMultipleAsync(Vehicles.VehiclesBasics_Filter[] filter, string bookmarkKey, int setSize)
        {
            Vehicles.ReadMultiple inValue = new Vehicles.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Vehicles.VehiclesBasics_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.IsUpdated_Result Vehicles.VehiclesBasics_Port.IsUpdated(Vehicles.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            Vehicles.IsUpdated inValue = new Vehicles.IsUpdated();
            inValue.Key = Key;
            Vehicles.IsUpdated_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vehicles.IsUpdated_Result> Vehicles.VehiclesBasics_Port.IsUpdatedAsync(Vehicles.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vehicles.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            Vehicles.IsUpdated inValue = new Vehicles.IsUpdated();
            inValue.Key = Key;
            return ((Vehicles.VehiclesBasics_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.GetRecIdFromKey_Result Vehicles.VehiclesBasics_Port.GetRecIdFromKey(Vehicles.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            Vehicles.GetRecIdFromKey inValue = new Vehicles.GetRecIdFromKey();
            inValue.Key = Key;
            Vehicles.GetRecIdFromKey_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vehicles.GetRecIdFromKey_Result> Vehicles.VehiclesBasics_Port.GetRecIdFromKeyAsync(Vehicles.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vehicles.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            Vehicles.GetRecIdFromKey inValue = new Vehicles.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Vehicles.VehiclesBasics_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.Create_Result Vehicles.VehiclesBasics_Port.Create(Vehicles.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref Vehicles.VehiclesBasics VehiclesBasics)
        {
            Vehicles.Create inValue = new Vehicles.Create();
            inValue.VehiclesBasics = VehiclesBasics;
            Vehicles.Create_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).Create(inValue);
            VehiclesBasics = retVal.VehiclesBasics;
        }
        
        public System.Threading.Tasks.Task<Vehicles.Create_Result> CreateAsync(Vehicles.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.CreateMultiple_Result Vehicles.VehiclesBasics_Port.CreateMultiple(Vehicles.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref Vehicles.VehiclesBasics[] VehiclesBasics_List)
        {
            Vehicles.CreateMultiple inValue = new Vehicles.CreateMultiple();
            inValue.VehiclesBasics_List = VehiclesBasics_List;
            Vehicles.CreateMultiple_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).CreateMultiple(inValue);
            VehiclesBasics_List = retVal.VehiclesBasics_List;
        }
        
        public System.Threading.Tasks.Task<Vehicles.CreateMultiple_Result> CreateMultipleAsync(Vehicles.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.Update_Result Vehicles.VehiclesBasics_Port.Update(Vehicles.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref Vehicles.VehiclesBasics VehiclesBasics)
        {
            Vehicles.Update inValue = new Vehicles.Update();
            inValue.VehiclesBasics = VehiclesBasics;
            Vehicles.Update_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).Update(inValue);
            VehiclesBasics = retVal.VehiclesBasics;
        }
        
        public System.Threading.Tasks.Task<Vehicles.Update_Result> UpdateAsync(Vehicles.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.UpdateMultiple_Result Vehicles.VehiclesBasics_Port.UpdateMultiple(Vehicles.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref Vehicles.VehiclesBasics[] VehiclesBasics_List)
        {
            Vehicles.UpdateMultiple inValue = new Vehicles.UpdateMultiple();
            inValue.VehiclesBasics_List = VehiclesBasics_List;
            Vehicles.UpdateMultiple_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).UpdateMultiple(inValue);
            VehiclesBasics_List = retVal.VehiclesBasics_List;
        }
        
        public System.Threading.Tasks.Task<Vehicles.UpdateMultiple_Result> UpdateMultipleAsync(Vehicles.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vehicles.Delete_Result Vehicles.VehiclesBasics_Port.Delete(Vehicles.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            Vehicles.Delete inValue = new Vehicles.Delete();
            inValue.Key = Key;
            Vehicles.Delete_Result retVal = ((Vehicles.VehiclesBasics_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vehicles.Delete_Result> Vehicles.VehiclesBasics_Port.DeleteAsync(Vehicles.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vehicles.Delete_Result> DeleteAsync(string Key)
        {
            Vehicles.Delete inValue = new Vehicles.Delete();
            inValue.Key = Key;
            return ((Vehicles.VehiclesBasics_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VehiclesBasics_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VehiclesBasics_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://nav.trimline.co.ke:1247/RemboService/WS/REMBO/Page/VehiclesBasics");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VehiclesBasics_PortClient.GetBindingForEndpoint(EndpointConfiguration.VehiclesBasics_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VehiclesBasics_PortClient.GetEndpointAddress(EndpointConfiguration.VehiclesBasics_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            VehiclesBasics_Port,
        }
    }
}
