//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posting
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", ConfigurationName="Posting.MBranch_Port")]
    public interface MBranch_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Post_Result) of message Post_Result does not match the default value (Post)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:Post", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Posting.Post_Result Post(Posting.Post request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:Post", ReplyAction="*")]
        System.Threading.Tasks.Task<Posting.Post_Result> PostAsync(Posting.Post request);
        
        // CODEGEN: Generating message contract since the wrapper name (Sendsms_Result) of message Sendsms_Result does not match the default value (Sendsms)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:Sendsms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Posting.Sendsms_Result Sendsms(Posting.Sendsms request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:Sendsms", ReplyAction="*")]
        System.Threading.Tasks.Task<Posting.Sendsms_Result> SendsmsAsync(Posting.Sendsms request);
        
        // CODEGEN: Generating message contract since the wrapper name (SendMessages_Result) of message SendMessages_Result does not match the default value (SendMessages)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:SendMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Posting.SendMessages_Result SendMessages(Posting.SendMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:SendMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<Posting.SendMessages_Result> SendMessagesAsync(Posting.SendMessages request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateRepaymentSchedule_Result) of message CreateRepaymentSchedule_Result does not match the default value (CreateRepaymentSchedule)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:CreateRepaymentSchedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Posting.CreateRepaymentSchedule_Result CreateRepaymentSchedule(Posting.CreateRepaymentSchedule request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/MBranch:CreateRepaymentSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<Posting.CreateRepaymentSchedule_Result> CreateRepaymentScheduleAsync(Posting.CreateRepaymentSchedule request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Post", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class Post
    {
        
        public Post()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Post_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class Post_Result
    {
        
        public Post_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sendsms", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class Sendsms
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=0)]
        public string source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=1)]
        public string telephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=2)]
        public string textsms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=3)]
        public string documentNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dates;
        
        public Sendsms()
        {
        }
        
        public Sendsms(string source, string telephone, string textsms, string documentNo, System.DateTime dates)
        {
            this.source = source;
            this.telephone = telephone;
            this.textsms = textsms;
            this.documentNo = documentNo;
            this.dates = dates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sendsms_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class Sendsms_Result
    {
        
        public Sendsms_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessages", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class SendMessages
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime date;
        
        public SendMessages()
        {
        }
        
        public SendMessages(System.DateTime date)
        {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessages_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class SendMessages_Result
    {
        
        public SendMessages_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateRepaymentSchedule", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class CreateRepaymentSchedule
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", Order=0)]
        public string loanNo;
        
        public CreateRepaymentSchedule()
        {
        }
        
        public CreateRepaymentSchedule(string loanNo)
        {
            this.loanNo = loanNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateRepaymentSchedule_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/MBranch", IsWrapped=true)]
    public partial class CreateRepaymentSchedule_Result
    {
        
        public CreateRepaymentSchedule_Result()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface MBranch_PortChannel : Posting.MBranch_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MBranch_PortClient : System.ServiceModel.ClientBase<Posting.MBranch_Port>, Posting.MBranch_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MBranch_PortClient() : 
                base(MBranch_PortClient.GetDefaultBinding(), MBranch_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MBranch_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MBranch_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(MBranch_PortClient.GetBindingForEndpoint(endpointConfiguration), MBranch_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MBranch_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MBranch_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MBranch_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MBranch_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MBranch_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Posting.Post_Result Posting.MBranch_Port.Post(Posting.Post request)
        {
            return base.Channel.Post(request);
        }
        
        public void Post()
        {
            Posting.Post inValue = new Posting.Post();
            Posting.Post_Result retVal = ((Posting.MBranch_Port)(this)).Post(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Posting.Post_Result> Posting.MBranch_Port.PostAsync(Posting.Post request)
        {
            return base.Channel.PostAsync(request);
        }
        
        public System.Threading.Tasks.Task<Posting.Post_Result> PostAsync()
        {
            Posting.Post inValue = new Posting.Post();
            return ((Posting.MBranch_Port)(this)).PostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Posting.Sendsms_Result Posting.MBranch_Port.Sendsms(Posting.Sendsms request)
        {
            return base.Channel.Sendsms(request);
        }
        
        public void Sendsms(string source, string telephone, string textsms, string documentNo, System.DateTime dates)
        {
            Posting.Sendsms inValue = new Posting.Sendsms();
            inValue.source = source;
            inValue.telephone = telephone;
            inValue.textsms = textsms;
            inValue.documentNo = documentNo;
            inValue.dates = dates;
            Posting.Sendsms_Result retVal = ((Posting.MBranch_Port)(this)).Sendsms(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Posting.Sendsms_Result> Posting.MBranch_Port.SendsmsAsync(Posting.Sendsms request)
        {
            return base.Channel.SendsmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Posting.Sendsms_Result> SendsmsAsync(string source, string telephone, string textsms, string documentNo, System.DateTime dates)
        {
            Posting.Sendsms inValue = new Posting.Sendsms();
            inValue.source = source;
            inValue.telephone = telephone;
            inValue.textsms = textsms;
            inValue.documentNo = documentNo;
            inValue.dates = dates;
            return ((Posting.MBranch_Port)(this)).SendsmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Posting.SendMessages_Result Posting.MBranch_Port.SendMessages(Posting.SendMessages request)
        {
            return base.Channel.SendMessages(request);
        }
        
        public void SendMessages(System.DateTime date)
        {
            Posting.SendMessages inValue = new Posting.SendMessages();
            inValue.date = date;
            Posting.SendMessages_Result retVal = ((Posting.MBranch_Port)(this)).SendMessages(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Posting.SendMessages_Result> Posting.MBranch_Port.SendMessagesAsync(Posting.SendMessages request)
        {
            return base.Channel.SendMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Posting.SendMessages_Result> SendMessagesAsync(System.DateTime date)
        {
            Posting.SendMessages inValue = new Posting.SendMessages();
            inValue.date = date;
            return ((Posting.MBranch_Port)(this)).SendMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Posting.CreateRepaymentSchedule_Result Posting.MBranch_Port.CreateRepaymentSchedule(Posting.CreateRepaymentSchedule request)
        {
            return base.Channel.CreateRepaymentSchedule(request);
        }
        
        public void CreateRepaymentSchedule(string loanNo)
        {
            Posting.CreateRepaymentSchedule inValue = new Posting.CreateRepaymentSchedule();
            inValue.loanNo = loanNo;
            Posting.CreateRepaymentSchedule_Result retVal = ((Posting.MBranch_Port)(this)).CreateRepaymentSchedule(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Posting.CreateRepaymentSchedule_Result> Posting.MBranch_Port.CreateRepaymentScheduleAsync(Posting.CreateRepaymentSchedule request)
        {
            return base.Channel.CreateRepaymentScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Posting.CreateRepaymentSchedule_Result> CreateRepaymentScheduleAsync(string loanNo)
        {
            Posting.CreateRepaymentSchedule inValue = new Posting.CreateRepaymentSchedule();
            inValue.loanNo = loanNo;
            return ((Posting.MBranch_Port)(this)).CreateRepaymentScheduleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MBranch_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MBranch_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://nav.trimline.co.ke:1247/RemboService/WS/REMBO/Codeunit/MBranch");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MBranch_PortClient.GetBindingForEndpoint(EndpointConfiguration.MBranch_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MBranch_PortClient.GetEndpointAddress(EndpointConfiguration.MBranch_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            MBranch_Port,
        }
    }
}
