//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MpesaCon
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", ConfigurationName="MpesaCon.MpesaConfig_Port")]
    public interface MpesaConfig_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.Read_Result Read(MpesaCon.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.Read_Result> ReadAsync(MpesaCon.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.ReadByRecId_Result ReadByRecId(MpesaCon.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.ReadByRecId_Result> ReadByRecIdAsync(MpesaCon.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.ReadMultiple_Result ReadMultiple(MpesaCon.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.ReadMultiple_Result> ReadMultipleAsync(MpesaCon.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.IsUpdated_Result IsUpdated(MpesaCon.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.IsUpdated_Result> IsUpdatedAsync(MpesaCon.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.GetRecIdFromKey_Result GetRecIdFromKey(MpesaCon.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(MpesaCon.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.Create_Result Create(MpesaCon.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.Create_Result> CreateAsync(MpesaCon.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.CreateMultiple_Result CreateMultiple(MpesaCon.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.CreateMultiple_Result> CreateMultipleAsync(MpesaCon.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.Update_Result Update(MpesaCon.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.Update_Result> UpdateAsync(MpesaCon.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.UpdateMultiple_Result UpdateMultiple(MpesaCon.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.UpdateMultiple_Result> UpdateMultipleAsync(MpesaCon.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MpesaCon.Delete_Result Delete(MpesaCon.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/mpesaconfig:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<MpesaCon.Delete_Result> DeleteAsync(MpesaCon.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig")]
    public partial class MpesaConfig
    {
        
        private string keyField;
        
        private string primary_KeyField;
        
        private string consumer_KeyField;
        
        private string consumer_SecretField;
        
        private string short_CodeField;
        
        private string passkeyField;
        
        private string merchant_NameField;
        
        private Transaction_Code transaction_CodeField;
        
        private bool transaction_CodeFieldSpecified;
        
        private Environment environmentField;
        
        private bool environmentFieldSpecified;
        
        private string sandbox_URLField;
        
        private string production_URLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Primary_Key
        {
            get
            {
                return this.primary_KeyField;
            }
            set
            {
                this.primary_KeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Consumer_Key
        {
            get
            {
                return this.consumer_KeyField;
            }
            set
            {
                this.consumer_KeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Consumer_Secret
        {
            get
            {
                return this.consumer_SecretField;
            }
            set
            {
                this.consumer_SecretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Short_Code
        {
            get
            {
                return this.short_CodeField;
            }
            set
            {
                this.short_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Passkey
        {
            get
            {
                return this.passkeyField;
            }
            set
            {
                this.passkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Merchant_Name
        {
            get
            {
                return this.merchant_NameField;
            }
            set
            {
                this.merchant_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Transaction_Code Transaction_Code
        {
            get
            {
                return this.transaction_CodeField;
            }
            set
            {
                this.transaction_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transaction_CodeSpecified
        {
            get
            {
                return this.transaction_CodeFieldSpecified;
            }
            set
            {
                this.transaction_CodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Environment Environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnvironmentSpecified
        {
            get
            {
                return this.environmentFieldSpecified;
            }
            set
            {
                this.environmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sandbox_URL
        {
            get
            {
                return this.sandbox_URLField;
            }
            set
            {
                this.sandbox_URLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Production_URL
        {
            get
            {
                return this.production_URLField;
            }
            set
            {
                this.production_URLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig")]
    public enum Transaction_Code
    {
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        WA,
        
        /// <remarks/>
        SB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig")]
    public enum Environment
    {
        
        /// <remarks/>
        Sandbox,
        
        /// <remarks/>
        Production,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig")]
    public partial class MpesaConfig_Filter
    {
        
        private MpesaConfig_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MpesaConfig_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig")]
    public enum MpesaConfig_Fields
    {
        
        /// <remarks/>
        Primary_Key,
        
        /// <remarks/>
        Consumer_Key,
        
        /// <remarks/>
        Consumer_Secret,
        
        /// <remarks/>
        Short_Code,
        
        /// <remarks/>
        Passkey,
        
        /// <remarks/>
        Merchant_Name,
        
        /// <remarks/>
        Transaction_Code,
        
        /// <remarks/>
        Environment,
        
        /// <remarks/>
        Sandbox_URL,
        
        /// <remarks/>
        Production_URL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public string Primary_Key;
        
        public Read()
        {
        }
        
        public Read(string Primary_Key)
        {
            this.Primary_Key = Primary_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public MpesaCon.MpesaConfig MpesaConfig;
        
        public Read_Result()
        {
        }
        
        public Read_Result(MpesaCon.MpesaConfig MpesaConfig)
        {
            this.MpesaConfig = MpesaConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public MpesaCon.MpesaConfig MpesaConfig;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(MpesaCon.MpesaConfig MpesaConfig)
        {
            this.MpesaConfig = MpesaConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public MpesaCon.MpesaConfig_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(MpesaCon.MpesaConfig_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MpesaCon.MpesaConfig[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(MpesaCon.MpesaConfig[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public MpesaCon.MpesaConfig MpesaConfig;
        
        public Create()
        {
        }
        
        public Create(MpesaCon.MpesaConfig MpesaConfig)
        {
            this.MpesaConfig = MpesaConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public MpesaCon.MpesaConfig MpesaConfig;
        
        public Create_Result()
        {
        }
        
        public Create_Result(MpesaCon.MpesaConfig MpesaConfig)
        {
            this.MpesaConfig = MpesaConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MpesaCon.MpesaConfig[] MpesaConfig_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(MpesaCon.MpesaConfig[] MpesaConfig_List)
        {
            this.MpesaConfig_List = MpesaConfig_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MpesaCon.MpesaConfig[] MpesaConfig_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(MpesaCon.MpesaConfig[] MpesaConfig_List)
        {
            this.MpesaConfig_List = MpesaConfig_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public MpesaCon.MpesaConfig MpesaConfig;
        
        public Update()
        {
        }
        
        public Update(MpesaCon.MpesaConfig MpesaConfig)
        {
            this.MpesaConfig = MpesaConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public MpesaCon.MpesaConfig MpesaConfig;
        
        public Update_Result()
        {
        }
        
        public Update_Result(MpesaCon.MpesaConfig MpesaConfig)
        {
            this.MpesaConfig = MpesaConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MpesaCon.MpesaConfig[] MpesaConfig_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(MpesaCon.MpesaConfig[] MpesaConfig_List)
        {
            this.MpesaConfig_List = MpesaConfig_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MpesaCon.MpesaConfig[] MpesaConfig_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(MpesaCon.MpesaConfig[] MpesaConfig_List)
        {
            this.MpesaConfig_List = MpesaConfig_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/mpesaconfig", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface MpesaConfig_PortChannel : MpesaCon.MpesaConfig_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MpesaConfig_PortClient : System.ServiceModel.ClientBase<MpesaCon.MpesaConfig_Port>, MpesaCon.MpesaConfig_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MpesaConfig_PortClient() : 
                base(MpesaConfig_PortClient.GetDefaultBinding(), MpesaConfig_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MpesaConfig_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpesaConfig_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(MpesaConfig_PortClient.GetBindingForEndpoint(endpointConfiguration), MpesaConfig_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpesaConfig_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MpesaConfig_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpesaConfig_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MpesaConfig_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpesaConfig_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.Read_Result MpesaCon.MpesaConfig_Port.Read(MpesaCon.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public MpesaCon.MpesaConfig Read(string Primary_Key)
        {
            MpesaCon.Read inValue = new MpesaCon.Read();
            inValue.Primary_Key = Primary_Key;
            MpesaCon.Read_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).Read(inValue);
            return retVal.MpesaConfig;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MpesaCon.Read_Result> MpesaCon.MpesaConfig_Port.ReadAsync(MpesaCon.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<MpesaCon.Read_Result> ReadAsync(string Primary_Key)
        {
            MpesaCon.Read inValue = new MpesaCon.Read();
            inValue.Primary_Key = Primary_Key;
            return ((MpesaCon.MpesaConfig_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.ReadByRecId_Result MpesaCon.MpesaConfig_Port.ReadByRecId(MpesaCon.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public MpesaCon.MpesaConfig ReadByRecId(string recId)
        {
            MpesaCon.ReadByRecId inValue = new MpesaCon.ReadByRecId();
            inValue.recId = recId;
            MpesaCon.ReadByRecId_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).ReadByRecId(inValue);
            return retVal.MpesaConfig;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MpesaCon.ReadByRecId_Result> MpesaCon.MpesaConfig_Port.ReadByRecIdAsync(MpesaCon.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MpesaCon.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            MpesaCon.ReadByRecId inValue = new MpesaCon.ReadByRecId();
            inValue.recId = recId;
            return ((MpesaCon.MpesaConfig_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.ReadMultiple_Result MpesaCon.MpesaConfig_Port.ReadMultiple(MpesaCon.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public MpesaCon.MpesaConfig[] ReadMultiple(MpesaCon.MpesaConfig_Filter[] filter, string bookmarkKey, int setSize)
        {
            MpesaCon.ReadMultiple inValue = new MpesaCon.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            MpesaCon.ReadMultiple_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MpesaCon.ReadMultiple_Result> MpesaCon.MpesaConfig_Port.ReadMultipleAsync(MpesaCon.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MpesaCon.ReadMultiple_Result> ReadMultipleAsync(MpesaCon.MpesaConfig_Filter[] filter, string bookmarkKey, int setSize)
        {
            MpesaCon.ReadMultiple inValue = new MpesaCon.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((MpesaCon.MpesaConfig_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.IsUpdated_Result MpesaCon.MpesaConfig_Port.IsUpdated(MpesaCon.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            MpesaCon.IsUpdated inValue = new MpesaCon.IsUpdated();
            inValue.Key = Key;
            MpesaCon.IsUpdated_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MpesaCon.IsUpdated_Result> MpesaCon.MpesaConfig_Port.IsUpdatedAsync(MpesaCon.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MpesaCon.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            MpesaCon.IsUpdated inValue = new MpesaCon.IsUpdated();
            inValue.Key = Key;
            return ((MpesaCon.MpesaConfig_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.GetRecIdFromKey_Result MpesaCon.MpesaConfig_Port.GetRecIdFromKey(MpesaCon.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            MpesaCon.GetRecIdFromKey inValue = new MpesaCon.GetRecIdFromKey();
            inValue.Key = Key;
            MpesaCon.GetRecIdFromKey_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MpesaCon.GetRecIdFromKey_Result> MpesaCon.MpesaConfig_Port.GetRecIdFromKeyAsync(MpesaCon.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MpesaCon.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            MpesaCon.GetRecIdFromKey inValue = new MpesaCon.GetRecIdFromKey();
            inValue.Key = Key;
            return ((MpesaCon.MpesaConfig_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.Create_Result MpesaCon.MpesaConfig_Port.Create(MpesaCon.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref MpesaCon.MpesaConfig MpesaConfig)
        {
            MpesaCon.Create inValue = new MpesaCon.Create();
            inValue.MpesaConfig = MpesaConfig;
            MpesaCon.Create_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).Create(inValue);
            MpesaConfig = retVal.MpesaConfig;
        }
        
        public System.Threading.Tasks.Task<MpesaCon.Create_Result> CreateAsync(MpesaCon.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.CreateMultiple_Result MpesaCon.MpesaConfig_Port.CreateMultiple(MpesaCon.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref MpesaCon.MpesaConfig[] MpesaConfig_List)
        {
            MpesaCon.CreateMultiple inValue = new MpesaCon.CreateMultiple();
            inValue.MpesaConfig_List = MpesaConfig_List;
            MpesaCon.CreateMultiple_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).CreateMultiple(inValue);
            MpesaConfig_List = retVal.MpesaConfig_List;
        }
        
        public System.Threading.Tasks.Task<MpesaCon.CreateMultiple_Result> CreateMultipleAsync(MpesaCon.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.Update_Result MpesaCon.MpesaConfig_Port.Update(MpesaCon.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref MpesaCon.MpesaConfig MpesaConfig)
        {
            MpesaCon.Update inValue = new MpesaCon.Update();
            inValue.MpesaConfig = MpesaConfig;
            MpesaCon.Update_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).Update(inValue);
            MpesaConfig = retVal.MpesaConfig;
        }
        
        public System.Threading.Tasks.Task<MpesaCon.Update_Result> UpdateAsync(MpesaCon.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.UpdateMultiple_Result MpesaCon.MpesaConfig_Port.UpdateMultiple(MpesaCon.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref MpesaCon.MpesaConfig[] MpesaConfig_List)
        {
            MpesaCon.UpdateMultiple inValue = new MpesaCon.UpdateMultiple();
            inValue.MpesaConfig_List = MpesaConfig_List;
            MpesaCon.UpdateMultiple_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).UpdateMultiple(inValue);
            MpesaConfig_List = retVal.MpesaConfig_List;
        }
        
        public System.Threading.Tasks.Task<MpesaCon.UpdateMultiple_Result> UpdateMultipleAsync(MpesaCon.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MpesaCon.Delete_Result MpesaCon.MpesaConfig_Port.Delete(MpesaCon.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            MpesaCon.Delete inValue = new MpesaCon.Delete();
            inValue.Key = Key;
            MpesaCon.Delete_Result retVal = ((MpesaCon.MpesaConfig_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MpesaCon.Delete_Result> MpesaCon.MpesaConfig_Port.DeleteAsync(MpesaCon.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MpesaCon.Delete_Result> DeleteAsync(string Key)
        {
            MpesaCon.Delete inValue = new MpesaCon.Delete();
            inValue.Key = Key;
            return ((MpesaCon.MpesaConfig_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MpesaConfig_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MpesaConfig_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://nav.trimline.co.ke:1247/RemboService/WS/REMBO/Page/MpesaConfig");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MpesaConfig_PortClient.GetBindingForEndpoint(EndpointConfiguration.MpesaConfig_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MpesaConfig_PortClient.GetEndpointAddress(EndpointConfiguration.MpesaConfig_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            MpesaConfig_Port,
        }
    }
}
