//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Batches
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", ConfigurationName="P_Batches.ParcelBatches_Port")]
    public interface ParcelBatches_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.Read_Result Read(P_Batches.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.Read_Result> ReadAsync(P_Batches.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.ReadByRecId_Result ReadByRecId(P_Batches.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.ReadByRecId_Result> ReadByRecIdAsync(P_Batches.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.ReadMultiple_Result ReadMultiple(P_Batches.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.ReadMultiple_Result> ReadMultipleAsync(P_Batches.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.IsUpdated_Result IsUpdated(P_Batches.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.IsUpdated_Result> IsUpdatedAsync(P_Batches.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.GetRecIdFromKey_Result GetRecIdFromKey(P_Batches.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(P_Batches.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.Create_Result Create(P_Batches.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.Create_Result> CreateAsync(P_Batches.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.CreateMultiple_Result CreateMultiple(P_Batches.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.CreateMultiple_Result> CreateMultipleAsync(P_Batches.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.Update_Result Update(P_Batches.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.Update_Result> UpdateAsync(P_Batches.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.UpdateMultiple_Result UpdateMultiple(P_Batches.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.UpdateMultiple_Result> UpdateMultipleAsync(P_Batches.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P_Batches.Delete_Result Delete(P_Batches.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/parcelbatches:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<P_Batches.Delete_Result> DeleteAsync(P_Batches.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches")]
    public partial class ParcelBatches
    {
        
        private string keyField;
        
        private string batch_NoField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string userField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string user_Agent_CodeField;
        
        private string user_NameField;
        
        private int parcel_CountField;
        
        private bool parcel_CountFieldSpecified;
        
        private decimal total_AmountField;
        
        private bool total_AmountFieldSpecified;
        
        private string from_LocationField;
        
        private string to_LocationField;
        
        private bool is_SyncedField;
        
        private bool is_SyncedFieldSpecified;
        
        private string sync_StatusField;
        
        private System.DateTime created_AtField;
        
        private bool created_AtFieldSpecified;
        
        private System.DateTime updated_AtField;
        
        private bool updated_AtFieldSpecified;
        
        private string parcel_Document_NosField;
        
        private string sourceField;
        
        private string destinationField;
        
        private string vehicleField;
        
        private string driverField;
        
        private System.DateTime dispatch_Date_TimeField;
        
        private bool dispatch_Date_TimeFieldSpecified;
        
        private System.DateTime received_Date_TimeField;
        
        private bool received_Date_TimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Batch_No
        {
            get
            {
                return this.batch_NoField;
            }
            set
            {
                this.batch_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string User_Agent_Code
        {
            get
            {
                return this.user_Agent_CodeField;
            }
            set
            {
                this.user_Agent_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string User_Name
        {
            get
            {
                return this.user_NameField;
            }
            set
            {
                this.user_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Parcel_Count
        {
            get
            {
                return this.parcel_CountField;
            }
            set
            {
                this.parcel_CountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parcel_CountSpecified
        {
            get
            {
                return this.parcel_CountFieldSpecified;
            }
            set
            {
                this.parcel_CountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Total_Amount
        {
            get
            {
                return this.total_AmountField;
            }
            set
            {
                this.total_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_AmountSpecified
        {
            get
            {
                return this.total_AmountFieldSpecified;
            }
            set
            {
                this.total_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string From_Location
        {
            get
            {
                return this.from_LocationField;
            }
            set
            {
                this.from_LocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string To_Location
        {
            get
            {
                return this.to_LocationField;
            }
            set
            {
                this.to_LocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Is_Synced
        {
            get
            {
                return this.is_SyncedField;
            }
            set
            {
                this.is_SyncedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Is_SyncedSpecified
        {
            get
            {
                return this.is_SyncedFieldSpecified;
            }
            set
            {
                this.is_SyncedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Sync_Status
        {
            get
            {
                return this.sync_StatusField;
            }
            set
            {
                this.sync_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime Created_At
        {
            get
            {
                return this.created_AtField;
            }
            set
            {
                this.created_AtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Created_AtSpecified
        {
            get
            {
                return this.created_AtFieldSpecified;
            }
            set
            {
                this.created_AtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime Updated_At
        {
            get
            {
                return this.updated_AtField;
            }
            set
            {
                this.updated_AtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Updated_AtSpecified
        {
            get
            {
                return this.updated_AtFieldSpecified;
            }
            set
            {
                this.updated_AtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Parcel_Document_Nos
        {
            get
            {
                return this.parcel_Document_NosField;
            }
            set
            {
                this.parcel_Document_NosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Vehicle
        {
            get
            {
                return this.vehicleField;
            }
            set
            {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Driver
        {
            get
            {
                return this.driverField;
            }
            set
            {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public System.DateTime Dispatch_Date_Time
        {
            get
            {
                return this.dispatch_Date_TimeField;
            }
            set
            {
                this.dispatch_Date_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Dispatch_Date_TimeSpecified
        {
            get
            {
                return this.dispatch_Date_TimeFieldSpecified;
            }
            set
            {
                this.dispatch_Date_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime Received_Date_Time
        {
            get
            {
                return this.received_Date_TimeField;
            }
            set
            {
                this.received_Date_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Received_Date_TimeSpecified
        {
            get
            {
                return this.received_Date_TimeFieldSpecified;
            }
            set
            {
                this.received_Date_TimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches")]
    public enum Status
    {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Intransit,
        
        /// <remarks/>
        Received,
        
        /// <remarks/>
        Collected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches")]
    public partial class ParcelBatches_Filter
    {
        
        private ParcelBatches_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ParcelBatches_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches")]
    public enum ParcelBatches_Fields
    {
        
        /// <remarks/>
        Batch_No,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        User_Agent_Code,
        
        /// <remarks/>
        User_Name,
        
        /// <remarks/>
        Parcel_Count,
        
        /// <remarks/>
        Total_Amount,
        
        /// <remarks/>
        From_Location,
        
        /// <remarks/>
        To_Location,
        
        /// <remarks/>
        Is_Synced,
        
        /// <remarks/>
        Sync_Status,
        
        /// <remarks/>
        Created_At,
        
        /// <remarks/>
        Updated_At,
        
        /// <remarks/>
        Parcel_Document_Nos,
        
        /// <remarks/>
        Source,
        
        /// <remarks/>
        Destination,
        
        /// <remarks/>
        Vehicle,
        
        /// <remarks/>
        Driver,
        
        /// <remarks/>
        Dispatch_Date_Time,
        
        /// <remarks/>
        Received_Date_Time,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public string Batch_No;
        
        public Read()
        {
        }
        
        public Read(string Batch_No)
        {
            this.Batch_No = Batch_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public P_Batches.ParcelBatches ParcelBatches;
        
        public Read_Result()
        {
        }
        
        public Read_Result(P_Batches.ParcelBatches ParcelBatches)
        {
            this.ParcelBatches = ParcelBatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public P_Batches.ParcelBatches ParcelBatches;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(P_Batches.ParcelBatches ParcelBatches)
        {
            this.ParcelBatches = ParcelBatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public P_Batches.ParcelBatches_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(P_Batches.ParcelBatches_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public P_Batches.ParcelBatches[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(P_Batches.ParcelBatches[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public P_Batches.ParcelBatches ParcelBatches;
        
        public Create()
        {
        }
        
        public Create(P_Batches.ParcelBatches ParcelBatches)
        {
            this.ParcelBatches = ParcelBatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public P_Batches.ParcelBatches ParcelBatches;
        
        public Create_Result()
        {
        }
        
        public Create_Result(P_Batches.ParcelBatches ParcelBatches)
        {
            this.ParcelBatches = ParcelBatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public P_Batches.ParcelBatches[] ParcelBatches_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(P_Batches.ParcelBatches[] ParcelBatches_List)
        {
            this.ParcelBatches_List = ParcelBatches_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public P_Batches.ParcelBatches[] ParcelBatches_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(P_Batches.ParcelBatches[] ParcelBatches_List)
        {
            this.ParcelBatches_List = ParcelBatches_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public P_Batches.ParcelBatches ParcelBatches;
        
        public Update()
        {
        }
        
        public Update(P_Batches.ParcelBatches ParcelBatches)
        {
            this.ParcelBatches = ParcelBatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public P_Batches.ParcelBatches ParcelBatches;
        
        public Update_Result()
        {
        }
        
        public Update_Result(P_Batches.ParcelBatches ParcelBatches)
        {
            this.ParcelBatches = ParcelBatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public P_Batches.ParcelBatches[] ParcelBatches_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(P_Batches.ParcelBatches[] ParcelBatches_List)
        {
            this.ParcelBatches_List = ParcelBatches_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public P_Batches.ParcelBatches[] ParcelBatches_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(P_Batches.ParcelBatches[] ParcelBatches_List)
        {
            this.ParcelBatches_List = ParcelBatches_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/parcelbatches", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/parcelbatches", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ParcelBatches_PortChannel : P_Batches.ParcelBatches_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ParcelBatches_PortClient : System.ServiceModel.ClientBase<P_Batches.ParcelBatches_Port>, P_Batches.ParcelBatches_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ParcelBatches_PortClient() : 
                base(ParcelBatches_PortClient.GetDefaultBinding(), ParcelBatches_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ParcelBatches_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParcelBatches_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(ParcelBatches_PortClient.GetBindingForEndpoint(endpointConfiguration), ParcelBatches_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParcelBatches_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ParcelBatches_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParcelBatches_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ParcelBatches_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParcelBatches_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.Read_Result P_Batches.ParcelBatches_Port.Read(P_Batches.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public P_Batches.ParcelBatches Read(string Batch_No)
        {
            P_Batches.Read inValue = new P_Batches.Read();
            inValue.Batch_No = Batch_No;
            P_Batches.Read_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).Read(inValue);
            return retVal.ParcelBatches;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P_Batches.Read_Result> P_Batches.ParcelBatches_Port.ReadAsync(P_Batches.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<P_Batches.Read_Result> ReadAsync(string Batch_No)
        {
            P_Batches.Read inValue = new P_Batches.Read();
            inValue.Batch_No = Batch_No;
            return ((P_Batches.ParcelBatches_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.ReadByRecId_Result P_Batches.ParcelBatches_Port.ReadByRecId(P_Batches.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public P_Batches.ParcelBatches ReadByRecId(string recId)
        {
            P_Batches.ReadByRecId inValue = new P_Batches.ReadByRecId();
            inValue.recId = recId;
            P_Batches.ReadByRecId_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).ReadByRecId(inValue);
            return retVal.ParcelBatches;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P_Batches.ReadByRecId_Result> P_Batches.ParcelBatches_Port.ReadByRecIdAsync(P_Batches.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<P_Batches.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            P_Batches.ReadByRecId inValue = new P_Batches.ReadByRecId();
            inValue.recId = recId;
            return ((P_Batches.ParcelBatches_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.ReadMultiple_Result P_Batches.ParcelBatches_Port.ReadMultiple(P_Batches.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public P_Batches.ParcelBatches[] ReadMultiple(P_Batches.ParcelBatches_Filter[] filter, string bookmarkKey, int setSize)
        {
            P_Batches.ReadMultiple inValue = new P_Batches.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            P_Batches.ReadMultiple_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P_Batches.ReadMultiple_Result> P_Batches.ParcelBatches_Port.ReadMultipleAsync(P_Batches.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<P_Batches.ReadMultiple_Result> ReadMultipleAsync(P_Batches.ParcelBatches_Filter[] filter, string bookmarkKey, int setSize)
        {
            P_Batches.ReadMultiple inValue = new P_Batches.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((P_Batches.ParcelBatches_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.IsUpdated_Result P_Batches.ParcelBatches_Port.IsUpdated(P_Batches.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            P_Batches.IsUpdated inValue = new P_Batches.IsUpdated();
            inValue.Key = Key;
            P_Batches.IsUpdated_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P_Batches.IsUpdated_Result> P_Batches.ParcelBatches_Port.IsUpdatedAsync(P_Batches.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<P_Batches.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            P_Batches.IsUpdated inValue = new P_Batches.IsUpdated();
            inValue.Key = Key;
            return ((P_Batches.ParcelBatches_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.GetRecIdFromKey_Result P_Batches.ParcelBatches_Port.GetRecIdFromKey(P_Batches.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            P_Batches.GetRecIdFromKey inValue = new P_Batches.GetRecIdFromKey();
            inValue.Key = Key;
            P_Batches.GetRecIdFromKey_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P_Batches.GetRecIdFromKey_Result> P_Batches.ParcelBatches_Port.GetRecIdFromKeyAsync(P_Batches.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<P_Batches.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            P_Batches.GetRecIdFromKey inValue = new P_Batches.GetRecIdFromKey();
            inValue.Key = Key;
            return ((P_Batches.ParcelBatches_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.Create_Result P_Batches.ParcelBatches_Port.Create(P_Batches.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref P_Batches.ParcelBatches ParcelBatches)
        {
            P_Batches.Create inValue = new P_Batches.Create();
            inValue.ParcelBatches = ParcelBatches;
            P_Batches.Create_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).Create(inValue);
            ParcelBatches = retVal.ParcelBatches;
        }
        
        public System.Threading.Tasks.Task<P_Batches.Create_Result> CreateAsync(P_Batches.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.CreateMultiple_Result P_Batches.ParcelBatches_Port.CreateMultiple(P_Batches.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref P_Batches.ParcelBatches[] ParcelBatches_List)
        {
            P_Batches.CreateMultiple inValue = new P_Batches.CreateMultiple();
            inValue.ParcelBatches_List = ParcelBatches_List;
            P_Batches.CreateMultiple_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).CreateMultiple(inValue);
            ParcelBatches_List = retVal.ParcelBatches_List;
        }
        
        public System.Threading.Tasks.Task<P_Batches.CreateMultiple_Result> CreateMultipleAsync(P_Batches.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.Update_Result P_Batches.ParcelBatches_Port.Update(P_Batches.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref P_Batches.ParcelBatches ParcelBatches)
        {
            P_Batches.Update inValue = new P_Batches.Update();
            inValue.ParcelBatches = ParcelBatches;
            P_Batches.Update_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).Update(inValue);
            ParcelBatches = retVal.ParcelBatches;
        }
        
        public System.Threading.Tasks.Task<P_Batches.Update_Result> UpdateAsync(P_Batches.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.UpdateMultiple_Result P_Batches.ParcelBatches_Port.UpdateMultiple(P_Batches.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref P_Batches.ParcelBatches[] ParcelBatches_List)
        {
            P_Batches.UpdateMultiple inValue = new P_Batches.UpdateMultiple();
            inValue.ParcelBatches_List = ParcelBatches_List;
            P_Batches.UpdateMultiple_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).UpdateMultiple(inValue);
            ParcelBatches_List = retVal.ParcelBatches_List;
        }
        
        public System.Threading.Tasks.Task<P_Batches.UpdateMultiple_Result> UpdateMultipleAsync(P_Batches.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P_Batches.Delete_Result P_Batches.ParcelBatches_Port.Delete(P_Batches.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            P_Batches.Delete inValue = new P_Batches.Delete();
            inValue.Key = Key;
            P_Batches.Delete_Result retVal = ((P_Batches.ParcelBatches_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P_Batches.Delete_Result> P_Batches.ParcelBatches_Port.DeleteAsync(P_Batches.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<P_Batches.Delete_Result> DeleteAsync(string Key)
        {
            P_Batches.Delete inValue = new P_Batches.Delete();
            inValue.Key = Key;
            return ((P_Batches.ParcelBatches_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ParcelBatches_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ParcelBatches_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://nav.trimline.co.ke:1247/RemboService/WS/REMBO/Page/ParcelBatches");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ParcelBatches_PortClient.GetBindingForEndpoint(EndpointConfiguration.ParcelBatches_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ParcelBatches_PortClient.GetEndpointAddress(EndpointConfiguration.ParcelBatches_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            ParcelBatches_Port,
        }
    }
}
